spring:
  datasource:
    url: jdbc:mysql://172.20.18.18/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.20.18.18
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
wechat:
  mpAppId: wxbb21cf89b17b5220
  mpAppSecret: 2623cdc4e4098b2df6d1993ed575302f
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://keke123.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: _3Oks6uOdD1WkH8p0SYKQRg_SGIDIc_hxHxmzFVmhMI
projectUrl:
  wechatMpAuthorize: http://keke123.natapp1.cc
  wechatOpenAuthorize: http://keke123.natapp1.cc
  sell: http://keke123.natapp1.cc
