spring:
  datasource:
    url: jdbc:mysql://172.20.18.18/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"